name: Golang Integration

on:
  push:

env:
  GO_VERSION: "1.25"

jobs:
  integration:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: libsdl-org/setup-sdl@main
        name: Install SDL3
        id: sdl
        with:
          install-linux-dependencies: true
          version: 3-latest
          version-sdl-image: 3-latest
          add-to-environment: true

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install go dependencies
        run: go mod download

      - name: Generate code
        run: go generate ./...

      - name: Vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47 # v9
        with:
          version: v2.5

      - name: Build
        run: CGO_ENABLED=0 go build

      - name: Unit tests
        run: go test ./...

      - name: Run integration tests
        env:
          SDL_VIDEO_DRIVER: offscreen
        run: |
          COMMAND="./chip8-go --screenshot"
          TEST_DIR="./sub/chip8-test-suite/bin"
          RESULTS_DIR="./results"

          ./chip8-go --screenshot -e 40 $TEST_DIR/1-chip8-logo.ch8
          ./chip8-go --screenshot -e 20 $TEST_DIR/2-ibm-logo.ch8
          ./chip8-go --screenshot -e 310 $TEST_DIR/3-corax+.ch8
          ./chip8-go --screenshot -e 960 $TEST_DIR/4-flags.ch8
          ./chip8-go --screenshot -e 2500 -t 1 $TEST_DIR/5-quirks.ch8

          mkdir -p $RESULTS_DIR

          for img in $(ls | grep .jpg)
          do
            NEW_NAME=$(echo $img | sed -E 's/-[0-9]+././g')
            mv $img $NEW_NAME
            mv $NEW_NAME $RESULTS_DIR
          done

      - name: Commit results
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          add: "./results"
          message: "[ci] update test result screenshots"
          default_author: github_actions
