name: Golang Integration

on:
  push:

env:
  GO_VERSION: "1.25"

jobs:
  integration:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install go dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601 # v9
        with:
          version: v2.5

      - name: Build
        run: CGO_ENABLED=0 go build

      - name: Unit tests
        run: go test ./...

      - name: Run integration tests
        env:
          SDL_VIDEO_DRIVER: dummy
        run: |
          COMMAND="./chip8-go --screenshot"
          TEST_DIR="./sub/chip8-test-suite/bin"
          RESULTS_DIR="./results"

          mvimg () {
            for img in $(ls | grep .jpg)
            do
              NEW_NAME=$(echo $img | sed -E "s/-[0-9]+./$1./g")
              mv $img $NEW_NAME
              mv $NEW_NAME $RESULTS_DIR
            done
          }

          mkdir -p $RESULTS_DIR

          ./chip8-go $TEST_DIR/1-chip8-logo.ch8 --disable-audio --screenshot -e 50
          ./chip8-go $TEST_DIR/2-ibm-logo.ch8 --disable-audio --screenshot -e 50
          ./chip8-go $TEST_DIR/3-corax+.ch8 --disable-audio --screenshot -e 350
          ./chip8-go $TEST_DIR/4-flags.ch8 --disable-audio --screenshot -e 1000
          mvimg ""
          ./chip8-go $TEST_DIR/5-quirks.ch8 --disable-audio --screenshot -e 3000 -t 1 -m chip8
          mvimg "-chip8"
          ./chip8-go $TEST_DIR/5-quirks.ch8 --disable-audio --screenshot -e 3500 -t 2 -m super
          mvimg "-super"
          ./chip8-go $TEST_DIR/5-quirks.ch8 --disable-audio --screenshot -e 2000000 -t 3 -m xo
          mvimg "-xo"
          ./chip8-go $TEST_DIR/8-scrolling.ch8 --disable-audio --screenshot -e 300 -t 1
          mvimg "-super-lores"
          ./chip8-go $TEST_DIR/8-scrolling.ch8 --disable-audio --screenshot -e 300 -t 3
          mvimg "-super-hires"
          ./chip8-go $TEST_DIR/8-scrolling.ch8 --disable-audio --screenshot -e 350 -t 4
          mvimg "-xo-lores"
          ./chip8-go $TEST_DIR/8-scrolling.ch8 --disable-audio --screenshot -e 350 -t 5
          mvimg "-xo-hires"


          for img in $(ls | grep .jpg)
          do
            NEW_NAME=$(echo $img | sed -E 's/-[0-9]+././g')
            mv $img $NEW_NAME
            mv $NEW_NAME $RESULTS_DIR
          done

      - name: Commit results
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          add: "./results"
          message: "[ci] update test result screenshots"
          default_author: github_actions
