name: Golang Integration

on:
  push:

env:
  GO_VERSION: "1.25"

jobs:
  integration:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11-xserver-utils libwayland-dev weston

      - uses: libsdl-org/setup-sdl@main
        name: Install SDL3
        id: sdl
        with:
          install-linux-dependencies: true
          version: 3-latest
          version-sdl-image: 3-latest
          add-to-environment: true

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install go dependencies
        run: go mod download

      - name: Generate code
        run: go generate ./...

      - name: Vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: v2.5

      - name: Build
        run: CGO_ENABLED=0 go build

      - name: Unit tests
        run: go test ./...

      - name: Start weston
        run: |
          weston --backend=headless-backend.so --width=640 --height=320 &
          sleep 2

      - name: Run headless test
        env:
          SDL_VIDEO_DRIVER: dummy
        run: |
          EXIT_AFTER=1000
          COMMAND="./chip8-go-v2 --screenshot -e"
          TEST_DIR="./sub/chip8-test-suite/bin"
          RESULTS_DIR="./results"
          declare -a tests=("1-chip8-logo.ch8" "2-ibm-logo.ch8" "3-corax+.ch8" "4-flags.ch8")

          for test in "${tests[@]}"
          do
            $COMMAND $EXIT_AFTER $TEST_DIR/$test
          done

          EXIT_AFTER=2500
          TEST_FLAG="--test-flag 1"

          $COMMAND $EXIT_AFTER $TEST_FLAG $TEST_DIR/5-quirks.ch8

          mkdir -p $RESULTS_DIR

          for img in $(ls | grep .jpg)
          do
            NEW_NAME=$(echo $img | sed -E 's/-[0-9]+././g')
            mv $img $NEW_NAME
            mv $NEW_NAME $RESULTS_DIR
          done

      - name: Commit results
        uses: EndBug/add-and-commit@v9
        with:
          add: "./results"
